/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mypackage;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DURGA
 */
public class Adddiagnosisinfo extends javax.swing.JFrame
{

    /**
     * Creates new form Adddiagnosisinfo
     */
    public Adddiagnosisinfo()
    {
        initComponents();
        CommonClassImage_hms.addLabelBackgroundimage(lblback, "C:\\Users\\DURGA\\Documents\\NetBeansProjects\\Hospital_Management_System\\src\\main\\java\\images\\add new patient background.jpg");
    }
    public ArrayList<User> userList()
    {
        ArrayList<User> userList= new ArrayList<>();
        String URL = "jdbc:mysql://localhost:3306/hms";
        String usernameString="root";
        String passString="Zalte@2001";
        
        try
        {
            Connection con=DriverManager.getConnection(URL,usernameString,passString);
            Statement st=con.createStatement();
            int id=Integer.parseInt(txtpatient.getText());
            String queryString="select*from addpatientrecord where pid="+id;
            ResultSet stResultSet=st.executeQuery(queryString);
            User user;
            while(stResultSet.next())
            {
                user=new User(stResultSet.getInt("pid"),stResultSet.getString("name"),stResultSet.getLong("contact"),stResultSet.getInt("age"),stResultSet.getString("gender"),stResultSet.getString("bloodgp"),stResultSet.getString("address"),stResultSet.getString("anymajor"));
                userList.add(user);
            }
            
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error"+ e);
        }
        return userList;
    }
    public void showUser()
    {
        ArrayList<User> list=userList();
        DefaultTableModel model = (DefaultTableModel) Table_info.getModel();
        Object [] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getId();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getContactno();
            row[3]=list.get(i).getage();
            row[4]=list.get(i).getGender();
            row[5]=list.get(i).getBloodgp();
            row[6]=list.get(i).getAddress();
            row[7]=list.get(i).getAnymajor();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblpatientid = new javax.swing.JLabel();
        txtpatient = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtsymptons = new javax.swing.JTextField();
        txtdiagnosis = new javax.swing.JTextField();
        txtmedicines = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        wardrequired = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        wardtype = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_info = new javax.swing.JTable();
        lblback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpatientid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpatientid.setText("Patient ID");
        jPanel1.add(lblpatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        jPanel1.add(txtpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 184, -1));

        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\DURGA\\Documents\\NetBeansProjects\\Hospital_Management_System\\src\\main\\java\\images\\search.png")); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 40, 116, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Sympton's");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 201, 137, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Diagnosis");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 249, 137, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Medicines");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 302, 137, 30));
        jPanel1.add(txtsymptons, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 201, 160, 30));
        jPanel1.add(txtdiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 257, 160, 27));
        jPanel1.add(txtmedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 302, 160, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Ward Required?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 203, 137, 28));

        wardrequired.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wardrequired.setText("Yes");
        wardrequired.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                wardrequiredActionPerformed(evt);
            }
        });
        jPanel1.add(wardrequired, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 203, 85, 28));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Type of Ward");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 265, 137, 28));

        wardtype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wardtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Single", "Duo" }));
        jPanel1.add(wardtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 265, 108, 28));

        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon("C:\\Users\\DURGA\\Documents\\NetBeansProjects\\Hospital_Management_System\\src\\main\\java\\images\\save-icon--1.png")); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 406, 127, 31));

        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon("C:\\Users\\DURGA\\Documents\\NetBeansProjects\\Hospital_Management_System\\src\\main\\java\\images\\Close.png")); // NOI18N
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 116, 31));

        Table_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Patient Id", "Name", "Contact No", "Age", "Gender", "Blood Gp", "Address", "Any Major Disease"
            }
        ));
        jScrollPane2.setViewportView(Table_info);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 101, 768, 60));
        jPanel1.add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wardrequiredActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_wardrequiredActionPerformed
    {//GEN-HEADEREND:event_wardrequiredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardrequiredActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsearchActionPerformed
    {//GEN-HEADEREND:event_btnsearchActionPerformed
        String paString=txtpatient.getText();
        if(paString.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Patient Field should not be empty.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
         userList();
         showUser();
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnsaveActionPerformed
    {//GEN-HEADEREND:event_btnsaveActionPerformed
        int patientid=Integer.parseInt(txtpatient.getText());
        String symString=txtsymptons.getText();
        String DiaString=txtdiagnosis.getText();
        String medString=txtmedicines.getText();
        boolean val=wardrequired.isSelected();
        String wardreString="No";
        if(val==true)
        {
            wardreString="Yes";
        }
        String typeofwardString=(String) wardtype.getSelectedItem();
        
        if(symString.isEmpty()||DiaString.isEmpty()||medString.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"All Field must be filled.","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
            String URL = "jdbc:mysql://localhost:3306/hms";
            String username = "root";
            String pass = "Zalte@2001";
            try{
            Connection con=DriverManager.getConnection(URL,username,pass);
            PreparedStatement pst = con.prepareStatement(
            "INSERT INTO `hms`.`adddiagnosisinfo` (`pid`, `symptons`, `diagnosis`, `medicine`, `ward_required`, `type__ward`) VALUES (?,?,?,?,?,?)");
            pst.setInt(1,patientid);
            pst.setString(2,symString);
              pst.setString(3,DiaString);
              pst.setString(4,medString);
              pst.setString(5,wardreString);
              pst.setString(6,typeofwardString);
              pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Submitted Successfully!!","InfoMessage",JOptionPane.INFORMATION_MESSAGE);  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error "+e);
            }
            
            
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncloseActionPerformed
    {//GEN-HEADEREND:event_btncloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Adddiagnosisinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Adddiagnosisinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Adddiagnosisinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Adddiagnosisinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Adddiagnosisinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_info;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblpatientid;
    private javax.swing.JTextField txtdiagnosis;
    private javax.swing.JTextField txtmedicines;
    private javax.swing.JTextField txtpatient;
    private javax.swing.JTextField txtsymptons;
    private javax.swing.JCheckBox wardrequired;
    private javax.swing.JComboBox<String> wardtype;
    // End of variables declaration//GEN-END:variables
}
